[package]
name = "rwt"
version = "0.2.2"
description = "Rebel Web Tokens, similar in form and function to JSON Web Tokens"
readme = "README.md"
repository = "https://github.com/archer884/rwt"
license = "MIT/Apache-2.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
rust-crypto = "0.2.0"
rustc-serialize = "0.3.0"
serde = "0.8.0"
serde_json = "0.8.0"
